export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const USER_INFO = 'USER_INFO';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';

export const UPDATE_USER_INFO = 'USER_INFO';
export const UPDATE_USER_INFO_ERROR = 'USER_INFO_ERROR';

export const GET_RESET_TOKEN = 'GET_RESET_TOKEN';
export const GET_RESET_TOKEN_ERROR = 'GET_RESET_TOKEN_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const DELETE_USER_ACCOUNT = 'DELETE_USER_ACCOUNT';
export const DELETE_USER_ACCOUNT_ERROR = 'DELETE_USER_ACCOUNT_ERROR';

export const FETCH_SHOPPINGLISTS = 'FETCH_SHOPPINGLISTS';
export const FETCH_SHOPPINGLISTS_ERROR = 'FETCH_SHOPPINGLISTS_ERROR';

export const CREATE_SHOPPINGLIST = 'CREATE_SHOPPINGLIST';
export const CREATE_SHOPPINGLIST_ERROR = 'CREATE_SHOPPINGLIST_ERROR';

export const UPDATE_SHOPPINGLIST = 'UPDATE_SHOPPINGLIST';
export const UPDATE_SHOPPINGLIST_ERROR = 'UPDATE_SHOPPINGLIST_ERROR';

export const SHOPPINGLIST_DETAIL = 'SHOPPINGLIST_DETAIL';
export const SHOPPINGLIST_DETAIL_ERROR = 'SHOPPINGLIST_DETAIL_ERROR';

export const DELETE_SHOPPINGLIST = 'DELETE_SHOPPINGLIST';
export const DELETE_SHOPPINGLIST_ERROR = 'DELETE_SHOPPINGLIST_ERROR';

export const CREATE_SHOPPING_ITEM = 'CREATE_SHOPPING_ITEM';
export const CREATE_SHOPPING_ITEM_ERROR = 'CREATE_SHOPPING_ITEM_ERROR';

export const FETCH_SHOPPING_ITEMS = 'FETCH_SHOPPING_ITEMS';
export const FETCH_SHOPPING_ITEMS_ERROR = 'FETCH_SHOPPING_ITEMS_ERROR';

export const FETCH_SHOPPING_ITEM_DETAIL = 'FETCH_SHOPPING_ITEM_DETAIL';
export const FETCH_SHOPPING_ITEM_DETAIL_ERROR = 'FETCH_SHOPPING_ITEM_DETAIL_ERROR';

export const UPDATE_SHOPPING_ITEM_DETAIL = 'UPDATE_SHOPPING_ITEM_DETAIL';
export const UPDATE_SHOPPING_ITEM_DETAIL_ERROR = 'UPDATE_SHOPPING_ITEM_DETAIL_ERROR';

export const DEELETE_SHOPPING_ITEM = 'DEELETE_SHOPPING_ITEM';
export const DEELETE_SHOPPING_ITEM_ERROR = 'DEELETE_SHOPPING_ITEM_ERROR';

export const SEARCH = 'SEARCH';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const ITEM_ID = 'ITEM_ID';

export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SUCCESS_ALERT = 'SUCCESS_ALERT';
export const ERROR_ALERT = 'ERROR_ALERT';
export const WARNING_ALERT = 'WARNING_ALERT';

export const CLEAR_INTERNAL_STATE = 'CLEAR_INTERNAL_STATE';
